package com.maxasoft.fallaciesresource;

public class ListInfidels {

    public static final String[] ARRAY_FALLACIES = new String[]{
        /* 00 */ "Constructing a Logical Argument",
		/* 01 */ "Accent",
		/* 02 */ "Ad hoc",
		/* 03 */ "Affirmation of the consequent",
		/* 04 */ "Amphiboly",
		/* 05 */ "Anecdotal evidence",
		/* 06 */ "Argumentum ad antiquitatem",
		/* 07 */ "Argumentum ad baculum / Appeal to force",
		/* 08 */ "Argumentum ad crumenam",
		/* 09 */ "Argumentum ad hominem",
		/* 10 */ "Argumentum ad ignorantiam",
		/* 10 */ "Argumentum ad lazarum",
		/* 11 */ "Argumentum ad logicam",
		/* 12 */ "Argumentum ad misericordiam",
		/* 13 */ "Argumentum ad nauseam",
		/* 14 */ "Argumentum ad novitatem",
		/* 15 */ "Argumentum ad numerum",
		/* 16 */ "Argumentum ad populum",
		/* 17 */ "Argumentum ad verecundiam",
		/* 18 */ "Audiatur et altera pars",
		/* 19 */ "Bifurcation",
		/* 20 */ "Circulus in demonstrando",
		/* 20 */ "Complex question / Fallacy of interrogation / Fallacy of presupposition",
		/* 21 */ "Composition",
		/* 22 */ "Converse accident / Hasty generalization",
		/* 23 */ "Converting a conditional",
		/* 24 */ "Cum hoc ergo propter hoc",
		/* 25 */ "Denial of the antecedent",
		/* 26 */ "Dicto simpliciter / The fallacy of accident / Sweeping generalization",
		/* 27 */ "Division",
		/* 28 */ "Equivocation / Fallacy of four terms",
		/* 29 */ "Extended analogy",
		/* 30 */ "Ignoratio elenchi / Irrelevant conclusion",
		/* 30 */ "Natural Law fallacy / Appeal to Nature",
		/* 31 */ "No True Scotsman ... fallacy",
		/* 32 */ "Non causa pro causa",
		/* 33 */ "Non sequitur",
		/* 34 */ "Petitio principii / Begging the question",
		/* 35 */ "Plurium interrogationum / Many questions",
		/* 36 */ "Post hoc, ergo propter hoc",
		/* 37 */ "Red herring",
		/* 38 */ "Reification / Hypostatization",
		/* 39 */ "Shifting the burden of proof",
		/* 40 */ "Slippery slope argument",
		/* 41 */ "Straw man",
		/* 42 */ "Tu quoque",
		/* 43 */ "Undistributed Middle / A is based on B fallacies / ... is a type of ... fallacies",
    };

    public static final String[] ARRAY_URL = new String[]{
		/* 00 */ "ConstructingALogicalArgument.html",
		/* 01 */ "accent.html",
		/* 02 */ "adhoc.html",
		/* 03 */ "consequent.html",
		/* 04 */ "amphiboly.html",
		/* 05 */ "anecdotal.html",
		/* 06 */ "antiquitatem.html",
		/* 07 */ "baculum.html",
		/* 08 */ "crumenam.html",
		/* 09 */ "hominem.html",
		/* 10 */ "ignorantiam.html",
		/* 10 */ "lazarum.html",
		/* 11 */ "logicam.html",
		/* 12 */ "misericordiam.html",
		/* 13 */ "nauseam.html",
		/* 14 */ "novitatem.html",
		/* 15 */ "numerum.html",
		/* 16 */ "populum.html",
		/* 17 */ "authority.html",
		/* 18 */ "alterapars.html",
		/* 19 */ "bifurcation.html",
		/* 20 */ "circulus.html",
		/* 20 */ "complexq.html",
		/* 21 */ "composition.html",
		/* 22 */ "generalization.html",
		/* 23 */ "conditional.html",
		/* 24 */ "cumhoc.html",
		/* 25 */ "antecedent.html",
		/* 26 */ "accident.html",
		/* 27 */ "division.html",
		/* 28 */ "equivocation.html",
		/* 29 */ "analogy.html",
		/* 30 */ "elenchi.html",
		/* 30 */ "natural.html",
		/* 31 */ "scots.html",
		/* 32 */ "noncausa.html",
		/* 33 */ "nonseq.html",
		/* 34 */ "begging.html",
		/* 35 */ "manyq.html",
		/* 36 */ "posthoc.html",
		/* 37 */ "herring.html",
		/* 38 */ "reification.html",
		/* 39 */ "shifting.html",
		/* 40 */ "slope.html",
		/* 41 */ "strawman.html",
		/* 42 */ "tuquoque.html",
		/* 43 */ "isatype.html",
    };

}
