package com.maxasoft.fallaciesresource;

public class ListNizkor {

    public static final String[] ARRAY_FALLACIES = new String[]{
        /* 00 */ "Acknowledgement",
		/* 01 */ "Description of Fallacies",
		/* 02 */ "Ad Hominem",
		/* 03 */ "Ad Hominem Tu Quoque",
		/* 04 */ "Appeal to Authority",
		/* 05 */ "Appeal to Belief",
		/* 06 */ "Appeal to Common Practice", 
		/* 07 */ "Appeal to Consequences of a Belief",
		/* 08 */ "Appeal to Emotion",
		/* 09 */ "Appeal to Fear",
		/* 10 */ "Appeal to Flattery", 
		/* 11 */ "Appeal to Novelty",
		/* 12 */ "Appeal to Pity", 
		/* 13 */ "Appeal to Popularity",
		/* 14 */ "Appeal to Ridicule",
		/* 15 */ "Appeal to Spite", 
		/* 16 */ "Appeal to Tradition",
		/* 17 */ "Bandwagon",
		/* 18 */ "Begging the Question",
		/* 19 */ "Biased Sample",
		/* 20 */ "Burden of Proof",
		/* 21 */ "Circumstancial Ad Hominem",
		/* 22 */ "Composition",
		/* 23 */ "Confusing Cause and Effect",
		/* 24 */ "Division", 
		/* 25 */ "False Dilemma", 
		/* 26 */ "Gambler's Fallacy",
		/* 27 */ "Genetic Fallacy",
		/* 28 */ "Guilt by Association",
		/* 29 */ "Hasty Generalization",
		/* 30 */ "Ignoring a Common Cause",
		/* 31 */ "Middle Ground",
		/* 32 */ "Misleading Vividness",
		/* 33 */ "Personal Attack",
		/* 34 */ "Poisoning the Well", 
		/* 35 */ "Post Hoc", 
		/* 36 */ "Questionable Cause",
		/* 37 */ "Red Herring",
		/* 38 */ "Relativist Fallacy",
		/* 39 */ "Slippery Slope",
		/* 40 */ "Special Pleading",
		/* 41 */ "Spotlight",
		/* 42 */ "Straw Man",
		/* 43 */ "Two Wrongs Make a Right",
    };

    public static final String[] ARRAY_URL = new String[]{
		/* 00 */ "Acknowlegement.html",
		/* 01 */ "DescriptionOfFallacies.html",
		/* 02 */ "AdHominem.html",
		/* 03 */ "AdHominemTuQuoque.html",
		/* 04 */ "AppealToAuthority.html",
		/* 05 */ "AppealToBelief.html",
		/* 06 */ "AppealToCommonPractice.html", 
		/* 07 */ "AppealToConsequencesOfABelief.html",
		/* 08 */ "AppealToEmotion.html",
		/* 09 */ "AppealToFear.html",
		/* 10 */ "AppealToFlattery.html",
		/* 11 */ "AppealToNovelty.html",
		/* 12 */ "AppealToPity.html",
		/* 13 */ "AppealToPopularity.html",
		/* 14 */ "AppealToRidicule.html",
		/* 15 */ "AppealToSpite.html",
		/* 16 */ "AppealToTradition.html",
		/* 17 */ "Bandwagon.html",
		/* 18 */ "BeggingTheQuestion.html",
		/* 19 */ "BiasedSample.html",
		/* 20 */ "BurdenOfProof.html",
		/* 21 */ "CircumstantialAdHominem.html",
		/* 22 */ "Composition.html",
		/* 23 */ "ConfusingCauseAndEffect.html",
		/* 24 */ "Division.html",
		/* 25 */ "FalseDilemma.html",
		/* 26 */ "GamblersFallacy.html",
		/* 27 */ "GeneticFallacy.html",
		/* 28 */ "GuiltByAssociation.html",
		/* 29 */ "HastyGeneralization.html",
		/* 30 */ "IgnoringACommonCause.html",
		/* 31 */ "MiddleGround.html",
		/* 32 */ "MisleadingVividness.html",
		/* 33 */ "PersonalAttack.html",
		/* 34 */ "PoisoningTheWell.html",
		/* 35 */ "PostHoc.html",
		/* 36 */ "QuestionableCause.html",
		/* 37 */ "RedHerring.html",
		/* 38 */ "RelativistFallacy.html",
		/* 39 */ "SlipperySlope.html",
		/* 40 */ "SpecialPleading.html",
		/* 41 */ "Spotlight.html",
		/* 42 */ "StrawMan.html",
		/* 43 */ "TwoWrongsMakeARight.html",
    };

    public static class Record {
        public String sName;
        public String sUrl;

        Record(String s1, String s2) {
            sName = s1;
            sUrl = s2;
        }
    }

    public static final Record[] ArrayOfRecords = {
		/* 00 */ new Record("Acknowlegement", "Acknowlegement.html"),
		/* 01 */ new Record("Description of Fallacies", "DescriptionOfFallacies.html"),
		/* 02 */ new Record("Ad Hominem", "AdHominem.html"),
		/* 03 */ new Record("Ad Hominem Tu Quoque", "AdHominemTuQuoque.html"),
		/* 04 */ new Record("Appeal to Authority", "AppealToAuthority.html"),
		/* 05 */ new Record("Appeal to Belief", "AppealToBelief.html"),
		/* 06 */ new Record("Appeal to Common Practice", "AppealToCommonPractice.html"),
		/* 07 */ new Record("Appeal to Consequences of a Belief", "AppealToConsequencesOfABelief.html"),
		/* 08 */ new Record("Appeal to Emotion", "AppealToEmotion.html"),
		/* 09 */ new Record("Appeal to Fear", "AppealToFear.html"),
		/* 10 */ new Record("Appeal to Flattery", "AppealToFlattery.html"),
		/* 11 */ new Record("Appeal to Novelty", "AppealToNovelty.html"),
		/* 12 */ new Record("Appeal to Pity", "AppealToPity.html"),
		/* 13 */ new Record("Appeal to Popularity", "AppealToPopularity.html"),
		/* 14 */ new Record("Appeal to Ridicule", "AppealToRidicule.html"),
		/* 15 */ new Record("Appeal to Spite", "AppealToSpite.html"),
		/* 16 */ new Record("Appeal to Tradition", "AppealToTradition.html"),
		/* 17 */ new Record("Bandwagon", "Bandwagon.html"),
		/* 18 */ new Record("Begging the Question", "BeggingTheQuestion.html"),
		/* 19 */ new Record("Biased Sample", "BiasedSample.html"),
		/* 20 */ new Record("Burden of Proof", "BurdenOfProof.html"),
		/* 21 */ new Record("Circumstancial Ad Hominem", "CircumstantialAdHominem.html"),
		/* 22 */ new Record("Composition", "Composition.html"),
		/* 23 */ new Record("Confusing Cause and Effect", "ConfusingCauseAndEffect.html"),
		/* 24 */ new Record("Division", "Division.html"),
		/* 25 */ new Record("False Dilemma", "FalseDilemma.html"),
		/* 26 */ new Record("Gambler's Fallacy", "GamblersFallacy.html"),
		/* 27 */ new Record("Genetic Fallacy", "GeneticFallacy.html"),
		/* 28 */ new Record("Guilt by Association", "GuiltByAssociation.html"),
		/* 29 */ new Record("Hasty Generalization", "HastyGeneralization.html"),
		/* 30 */ new Record("Ignoring a Common Cause", "IgnoringACommonCause.html"),
		/* 31 */ new Record("Middle Ground", "MiddleGround.html"),
		/* 32 */ new Record("Misleading Vividness", "MisleadingVividness.html"),
		/* 33 */ new Record("Personal Attack", "PersonalAttack.html"),
		/* 34 */ new Record("Poisoning the Well", "PoisoningTheWell.html"),
		/* 35 */ new Record("Post Hoc", "PostHoc.html"),
		/* 36 */ new Record("Questionable Cause", "QuestionableCause.html"),
		/* 37 */ new Record("Red Herring", "RedHerring.html"),
		/* 38 */ new Record("Relativist Fallacy", "RelativistFallacy.html"),
		/* 39 */ new Record("Slippery Slope", "SlipperySlope.html"),
		/* 40 */ new Record("Special Pleading", "SpecialPleading.html"),
		/* 41 */ new Record("Spotlight", "Spotlight.html"),
		/* 42 */ new Record("Straw Man", "StrawMan.html"),
		/* 43 */ new Record("Two Wrongs Make a Right", "TwoWrongsMakeARight.html"),
    };

}
